<a href="https://colab.research.google.com/github/Rakshit-Sawarn-iitb/WIDS-Brain-Tumor-Detection/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **Initializing Array**

In [3]:
arr = np.array(
    [
        [1,2,4],
        [7,13,21]
    ]
)

print(arr)
print("Shape: ",arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape:  (2, 3)


### **Random Module**

In [4]:
n_rows = 2
n_columns = 3

x = np.random.randn(n_rows,n_columns)

print(x)

[[ 0.11758143 -1.66913208  0.43638077]
 [ 0.93055893 -0.0883409  -1.33877866]]


### **Array with all elements zeros or ones**

In [5]:
ZERO_ARR = np.zeros((4,5,2))

print(ZERO_ARR)

ONE_ARR = np.ones((4,5,2))

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### **Reshaping an array**

In [6]:
y = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

y_transpose = np.reshape(y,(3,2))
print(y_transpose)

y_flat = np.reshape(y,(6,1))
print(y_flat)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
y = np.array(
    [
    [4],
    [7],
    [11]
    ]
)
assert y.shape == (3,1)

print(y)

[[ 4]
 [ 7]
 [11]]


# **Indexing and Slicing**

In [8]:
x = np.array([4,1,5,6,11])
y = x[1:4]
print(y)

z = np.array([1,2,3,4,5,6,7,8,9,10])
w = z[0:9:2]
print(w)

[1 5 6]
[1 3 5 7 9]


In [9]:
arr_2d = np.array(
    [
        [4,5,2],
        [3,7,9],
        [1,4,5],
        [6,6,1]
    ]
)

sliced_arr_2d = arr_2d[0:3,1:]
print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


# **Broadcasting**

In [10]:
arr1 = np.array([1,2,3,4])
b = 1

arr1 = arr1+b

print(arr1)

arr2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
arr3 = np.array(
    [
        [4],
        [5]
    ]
)

arr2 = arr2*arr3

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


# **Vectorization**

In [11]:
import time
arr_nonvectorized = np.random.randn(1000,1000)
arr_vectorized = np.array(arr_nonvectorized)

start_nv = time.time()
rows,columns = arr_nonvectorized.shape
for i in range(rows):
  for j in range(columns):
    arr_nonvectorized[i,j] = arr_nonvectorized[i,j]*3
end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")
print(arr_nonvectorized)

start_v = time.time()
b = 3
arr_vectorized = arr_vectorized*b
end_v = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_v-start_v), "ms")
print(arr_vectorized)

Time taken in non-vectorized approach: 722.6989269256592 ms
[[ 1.59116723 -1.64029961 -0.96525927 ...  1.18130975 -3.61870095
  -0.44207767]
 [-4.65960686  0.9850866  -0.22961915 ... -0.09569572  3.64758692
   0.343137  ]
 [-0.63601225  6.88821485  2.76191303 ...  3.01359895  2.06941723
  -1.07487123]
 ...
 [-1.66836928  2.22697269 -0.02056081 ...  1.25623639 -0.03347828
  -0.04162802]
 [-5.60666973 -4.73831627 -3.28562484 ... -2.9028845  -0.43872983
  -3.93819645]
 [ 1.64008401 -2.68622362 -1.07547764 ... -4.60921297  1.56303205
   1.13652477]]
Time taken in non-vectorized approach: 4.87065315246582 ms
[[ 1.59116723 -1.64029961 -0.96525927 ...  1.18130975 -3.61870095
  -0.44207767]
 [-4.65960686  0.9850866  -0.22961915 ... -0.09569572  3.64758692
   0.343137  ]
 [-0.63601225  6.88821485  2.76191303 ...  3.01359895  2.06941723
  -1.07487123]
 ...
 [-1.66836928  2.22697269 -0.02056081 ...  1.25623639 -0.03347828
  -0.04162802]
 [-5.60666973 -4.73831627 -3.28562484 ... -2.9028845  -0.438