<a href="https://colab.research.google.com/github/Rakshit-Sawarn-iitb/WIDS-Brain-Tumor-Detection/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

In [ ]:
arr = np.array(
    [
        [1,2,4],
        [7,13,21]
    ]
)

print(arr)
print("Shape: ",arr.shape)

In [ ]:
n_rows = 2
n_columns = 3

x = np.random.randn(n_rows,n_columns)

print(x)

In [ ]:
ZERO_ARR = np.zeros((4,5,2))

print(ZERO_ARR)

ONE_ARR = np.ones((4,5,2))

print(ONE_ARR)

In [ ]:
y = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

y_transpose = np.reshape(y,(3,2))
print(y_transpose)

y_flat = np.reshape(y,(6,1))
print(y_flat)

In [ ]:
y = np.array(
    [
    [4],
    [7],
    [11]
    ]
)
assert y.shape == (3,1)

print(y)

In [ ]:
x = np.array([4,1,5,6,11])
y = x[1:4]
print(y)

z = np.array([1,2,3,4,5,6,7,8,9,10])
w = z[0:9:2]
print(w)

In [ ]:
arr_2d = np.array(
    [
        [4,5,2],
        [3,7,9],
        [1,4,5],
        [6,6,1]
    ]
)

sliced_arr_2d = arr_2d[0:3,1:]
print(sliced_arr_2d)

In [52]:
import numpy as np
arr1 = np.array([1,2,3,4])
b = 1

arr1 = arr1+b

print(arr1)

arr2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
arr3 = np.array(
    [
        [4],
        [5]
    ]
)

arr2 = arr2*arr3

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]
