<a href="https://colab.research.google.com/github/Rakshit-Sawarn-iitb/WIDS-Brain-Tumor-Detection/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

In [38]:
arr = np.array(
    [
        [1,2,4],
        [7,13,21]
    ]
)

print(arr)
print("Shape: ",arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape:  (2, 3)


In [39]:
n_rows = 2
n_columns = 3

x = np.random.randn(n_rows,n_columns)

print(x)

[[-0.27707664 -0.31875853 -0.48628413]
 [ 0.91287753  0.96639714 -2.42665826]]


In [40]:
ZERO_ARR = np.zeros((4,5,2))

print(ZERO_ARR)

ONE_ARR = np.ones((4,5,2))

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [41]:
y = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

y_transpose = np.reshape(y,(3,2))
print(y_transpose)

y_flat = np.reshape(y,(6,1))
print(y_flat)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [42]:
y = np.array(
    [
    [4],
    [7],
    [11]
    ]
)
assert y.shape == (3,1)

print(y)

[[ 4]
 [ 7]
 [11]]
